keycloakHostname: dbildungs-iam-keycloak
keycloakExternalHostname: 'keycloak.spshinfra.spsh.dbildungsplattform.de '
auth: 
  existingSecret: dbildungs-iam-server

database:
  name: dbildungs_iam_server
  username: dbildungs_iam_server
backendHostname: spsh.spshinfra.spsh.dbildungsplattform.de

backend: 
  image:
    pullPolicy: IfNotPresent

autoscaling:
  enabled: true

itslearning:
  enabled: false

privacyidea:
  url: https://privacyidea.spshinfra.spsh.dbildungsplattform.de
  renameWaitingTime: 3

system:
  rename_waiting_time_in_seconds: 3

cronjobs:
  enabled: true

kafka:
  enabled: true
  initEnabled: true
  sessionTimeout: 300000
  heartbeatInterval: 10000