keycloakHostname: dbildungs-iam-keycloak
keycloakExternalHostname: "login.schule-sh.de"
auth:
  existingSecret: dbildungs-iam-server

database:
  name: dbildungs_iam_server
  username: dbildungs_iam_server

backendHostname: portal.schule-sh.de
backend2ndHostname: ""

backend:
  env:
    stepUpTimeoutEnabled: "true"
  dbseeding:
    enabled: false
    command: ["node", "dist/src/console/main.js", "db", "seed", "prod"]
  resources:
    limits:
      cpu: 2
      memory: 4Gi
    requests:
      cpu: 1
      memory: 500Mi
  image:
    pullPolicy: IfNotPresent
  ingress:
    enabled2nd: false

ldap:
  url: ldaps://ldap-write.schule-sh.de
  base_dn: dc=schule-sh,dc=de
  retryWrapperDefaultRetries: 5

itslearning:
  enabled: true
  root: "sh"
  endpoint: "https://eu1enterprise.itslearning.com/WCFServiceLibrary/ImsEnterpriseServicesPort.svc"

autoscaling:
  enabled: true
  targetCPUUtilizationPercentage: 60
  minReplicas: 3
  maxReplicas: 10

privacyidea:
  url: https://privacyidea.spsh.dbildungsplattform.de
  renameWaitingTime: 3

system:
  rename_waiting_time_in_seconds: 3

status:
  url: "https://status.spsh.dbildungsplattform.de/"

ox:
  enabled: true
  username: "oxadmin"
  endpoint: "https://ox-provisioning.schule-sh.de/webservices/"
  contextId: "10"
  contextName: "context10"

email:
  nonEnabledEmailAddressesDeadlineInDays: 180

cronjobs:
  enabled: true

kafka:
  enabled: true
  initEnabled: true
  sessionTimeout: 300000
  heartbeatInterval: 10000

podDisruptionBudget:
  enabled: true
  minAvailable: "60%"

featureFlags:
  rolleErweitern: true
