keycloakHostname: login.schule-sh.de
auth: 
  existingSecret: dbildungs-iam-keycloak 
database:
  name: dbildungs_iam_keycloak
  username: dbildungs_iam_keycloak

image:
  pullPolicy: IfNotPresent

resources:
  limits:
    cpu: 4
    memory: 4Gi
  requests:
    cpu: 2
    memory: 1Gi

ingress:
  enabled2nd: false

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 8

status:
  url: "https://status.schule-sh.de/"

schoolsh:
  clientId: https://school-sh.schule-sh.de
  rootUrl: https://school-sh.schule-sh.de

podDisruptionBudget:
  enabled: true
  minAvailable: "60%"